default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: canihazadmin-dev

test:
  <<: *default
  database: test

production:
  <<: *default
  database: canihazadmin-prod
